"""Blender-authored reusable architecture kit; creates only its own scene.
Run through MCP, or with --background --factory-startup to save the source file.
"""
import bpy, math, json, os
from mathutils import Vector
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'assets', 'models')
scene = bpy.data.scenes.new('ONISOLO / Rain Court Architecture')
scene.world = bpy.data.worlds.new('Rain Court / Studio')
scene.world.color = (.16, .20, .23)
scene.render.engine = 'BLENDER_EEVEE'
if bpy.context.window: bpy.context.window.scene = scene
kit = {}

def mesh(name, vertices, faces, bevel=0):
    data = bpy.data.meshes.new('Rain Court / '+name)
    data.from_pydata([(x,-z,y) for x,y,z in vertices], [], faces)
    data.update()
    obj = bpy.data.objects.new(data.name, data); scene.collection.objects.link(obj)
    if bevel:
        mod = obj.modifiers.new('Hand cut edges', 'BEVEL'); mod.width=bevel; mod.segments=1
        mod.affect='EDGES'
    bpy.context.view_layer.update()
    evaluated=obj.evaluated_get(bpy.context.evaluated_depsgraph_get())
    final=evaluated.to_mesh(); final.calc_loop_triangles()
    p=[]
    for tri in final.loop_triangles:
        a,b,c=[final.vertices[i].co for i in tri.vertices]
        if (b-a).cross(c-a).length < .0000001: continue
        for index in tri.vertices:
            v=final.vertices[index].co; p.extend([round(v.x*10000),round(v.z*10000),round(-v.y*10000)])
    kit[name]={'p':p}
    evaluated.to_mesh_clear()
    obj.location.x=len(kit)*2-8
    return obj

cube=[(-.5,-.5,-.5),(.5,-.5,-.5),(.5,.5,-.5),(-.5,.5,-.5),(-.5,-.5,.5),(.5,-.5,.5),(.5,.5,.5),(-.5,.5,.5)]
faces=[(0,3,2,1),(4,5,6,7),(0,1,5,4),(3,7,6,2),(0,4,7,3),(1,2,6,5)]
mesh('stone',cube,faces,.07)
mesh('timber',cube,faces,.025)
mesh('paver',cube,faces,.055)
# A convex ceramic roof tile with a raised end lip and overlapping belly.
verts=[]; segments=8
for z in [-.5,.42,.5]:
    for i in range(segments+1):
        x=i/segments-.5
        y=.16*math.sqrt(max(0,1-(x*2)**2)) + (.07 if z==.5 else 0)
        verts.append((x,y,z))
tilefaces=[]
for row in range(2):
    for i in range(segments):
        a=row*(segments+1)+i;tilefaces.append((a,a+segments+1,a+segments+2,a+1))
mesh('tile',verts,tilefaces)
# Thick folded leaves; a single three-dimensional form catches sky and sun.
mesh('leaf',[(-.5,0,0),(0,.14,-.20),(.5,0,0),(0,-.015,.20),(0,.08,0)],[(0,4,1),(1,4,2),(2,4,3),(3,4,0),(1,2,3,0)])

def lathe(name, rings, sides=12):
    vs=[]
    for y,radius in rings:
        for i in range(sides):
            a=i*math.tau/sides;vs.append((math.cos(a)*radius,y,math.sin(a)*radius))
    fs=[tuple(reversed(range(sides))),tuple(range((len(rings)-1)*sides,len(rings)*sides))]
    for row in range(len(rings)-1):
        for i in range(sides):
            j=(i+1)%sides;fs.append((row*sides+i,row*sides+j,(row+1)*sides+j,(row+1)*sides+i))
    return mesh(name,vs,fs)

lathe('barrel',[(-.5,.40),(-.42,.46),(0,.5),(.42,.46),(.5,.40)])
lathe('lantern',[(-.5,.28),(-.40,.40),(-.22,.48),(.22,.48),(.40,.40),(.5,.28)],16)
lathe('finial',[(-.5,.5),(-.3,.5),(-.17,.20),(.25,.16),(.4,.35),(.5,0)],8)
mesh('rock',[(-.5,-.2,-.4),(.42,-.2,-.5),(.5,-.2,.32),(-.3,-.2,.5),(-.32,.27,-.25),(.18,.5,-.2),(.3,.2,.3),(-.15,.4,.25)],faces,.015)

mat=bpy.data.materials.new('Rain Court / Celadon');mat.diffuse_color=(.13,.25,.24,1)
for obj in scene.objects:
    if obj.type=='MESH':obj.data.materials.append(mat)
camdata=bpy.data.cameras.new('Rain Court / Kit camera');cam=bpy.data.objects.new(camdata.name,camdata);scene.collection.objects.link(cam)
cam.location=(7,-14,11);cam.rotation_euler=(Vector((1,0,0))-cam.location).to_track_quat('-Z','Y').to_euler();camdata.type='ORTHO';camdata.ortho_scale=21;scene.camera=cam
ld=bpy.data.lights.new('Rain Court / Key','AREA');lo=bpy.data.objects.new(ld.name,ld);scene.collection.objects.link(lo);lo.location=(0,-6,10);ld.energy=1600;ld.size=8
scene.render.resolution_x=1600;scene.render.resolution_y=700;scene.render.resolution_percentage=100
payload='// Blender architecture kit. Generated by tools/build-rain-kit.py.\nexport const RAIN_KIT = '+json.dumps(kit,separators=(',',':'))+';\n'
os.makedirs(OUT,exist_ok=True)
with open(os.path.join(OUT,'rain-court-kit.js'),'w') as f:f.write(payload)
if bpy.app.background:bpy.ops.wm.save_as_mainfile(filepath=os.path.join(OUT,'rain-court-kit.blend'),compress=True)
result={'scene':scene.name,'meshes':{k:len(v['p'])//9 for k,v in kit.items()},'bytes':len(payload)}
